
spring.application.name=gateway-service

# Enable Config Processing
spring.config.import=optional:classpath:models.yaml

# Resilience4j Rate Limiter Config
resilience4j.ratelimiter.instances.llmRateLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.llmRateLimiter.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.llmRateLimiter.timeoutDuration=5s

# Resilience4j Circuit Breaker Config
resilience4j.circuitbreaker.instances.llmCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.llmCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.llmCircuitBreaker.slidingWindowSize=10
